export const GET_CONTACT_REQUEST ="GET_CONTACT_REQUEST";
export const GET_CONTACT_SUCCESS ="GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAILURE ="GET_CONTACT_FAILURE";


export const GET_POST_CONTACT_REQUEST ="GET_POST_CONTACT_REQUEST";
export const GET_POST_CONTACT_SUCCESS ="GET_POST_CONTACT_SUCCESS";
export const GET_POST_CONTACT_FAILURE ="GET_POST_CONTACT_FAILURE";

export const UPDATE_CONTACT_REQUEST ="UPDATE_CONTACT_REQUEST";
export const UPDATE_CONTACT_SUCCESS ="UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAILURE ="UPDATE_CONTACT_FAILURE";

